---
services:
  recursor:
    # build:
    #   context: ./pdns/
    #   dockerfile: ./Dockerfile-recursor
    image: barisaku/pdns-recursor:latest
    container_name: pdns_recursor
    restart: always
    env_file:
      - api-key.env
    ports:
      - "53:53"
      - "53:53/udp"
      - "8082:8082"
    volumes:
      - ./conf/recursor.conf:/etc/powerdns/recursor.d/recursor.conf:ro
    networks:
      powerdns:
        ipv4_address: 172.23.0.2

  auth:
    # build:
    #   context: ./pdns/
    #   dockerfile: ./Dockerfile-auth
    image: barisaku/pdns-auth:latest
    container_name: pdns_auth
    restart: always
    env_file:
      - api-key.env
    ports:
      - "1053:53"
      - "1053:53/udp"
      - "8081:8081"
    volumes:
      - powerdns_auth:/var/lib/powerdns
      - ./conf/pdns.conf:/etc/powerdns/pdns.d/pdns.conf:ro
    networks:
      powerdns:
        ipv4_address: 172.23.0.3

  webapp:
    # build:
    #   context: ./PowerDNS-Admin/
    #   dockerfile: ./docker/Dockerfile
    image: barisaku/pdns-admin:latest
    container_name: pdns_admin
    restart: always
    ports:
      - "9191:80"
    logging:
      driver: json-file
      options:
        max-size: 50m
    environment:
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
    volumes:
      - powerdns_web:/data
    networks:
      powerdns:
        ipv4_address: 172.23.0.4

volumes:
  powerdns_auth:
    driver: local
  powerdns_web:
    driver: local

networks:
  powerdns:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1
